######################################
## free SH3 PCA analysis            ##
## author : Pascale Lemieux         ##
## Date : 2023-01-10                ##
######################################

library(tidyverse)
library(magrittr)
library(gtools)
library(mixtools)

##############################################
## Import raw data generated by pyphe-quant ##
##############################################

#  For prey array plates, final diploid selection plates and final MTX plates #
# Read array plan in 1536 format
plate1536 <-
 read.csv2('~/ancSH3_paper/SupplementaryMaterial/SupplementaryData1/free_SH3_RD/plate1536_freeSH3.csv')


# Set working directory with raw data from pyphe
setwd("~/ancSH3_paper/SupplementaryMaterial/SupplementaryData1/free_SH3_RD/S2_diploid/")
file = dir(pattern = ".csv")

# Assign names to each data frame object
j = 1
for (i in file) {
  assign(x = paste0('plate', j), read.csv(i))
  j = j + 1
  
}

# merge each data frame with array plan
n =16
for (i in 1:n) {
  
  p <- get(paste0('plate', i))
  assign('p',   
         merge(p, 
               plate1536, 
               by.x = c('row', 'column'), 
               by.y = c('row', 'col'), 
               all = T)
  )
  
  p$plate <- i
  assign(paste0('plate', i), p)
}

# assemble all data frame
all_plate <- 
  do.call(rbind.data.frame, mget(ls(pattern = "^plate.{1,2}$")))

# write file with data of each selection step
# MTX2_data.csv , diploid2_data.csv or DHFR3_data.csv
filename = '~/ancSH3_paper/SupplementaryMaterial/SupplementaryData1/free_SH3_RD/diploid2_data.csv'# MTX or diploid selection
  write.csv2(all_plate,
             file = filename,
             row.names = T,
             quote = F)

######################################
## Data verification  and filtering ##
######################################

#  Removal of non-growing position in the prey array and
#  diploid selection for the MTX data  #
#  Because the full-lenght paralog PCA experiment showed growth for 
#  all the prey tested here the DHFR3 array was not analysed

# Set working directory where all the previous files were generated
setwd('~/ancSH3_paper/SupplementaryMaterial/SupplementaryData1/free_SH3_RD/')

# Read assembled data 
MTX2_data <- 
  read.csv2(file = './MTX2_data.csv')

diploid2_data <- 
  read.csv2(file = './diploid2_data.csv')


# Verification of no growth positions in diploid2 selection plates
# Histogram of colony area distribution of diploid selection
ggplot(data = diploid2_data)+
  geom_histogram(mapping = aes(x = area),
                 binwidth = 20)+
  xlim(0, 8000)+
  geom_vline(xintercept = 500)+
  theme_minimal()

# remove position with diploid colony area < 500 from the data
diploid.to.with <- 
unique(diploid2_data[(diploid2_data$area) < 500, c('row', 'column')])
diploid.to.with$with <- TRUE

MTX2_data <- 
merge(MTX2_data, 
      diploid.to.with, 
      by = c('row', 'column'), 
      all = TRUE)
MTX2_data$with <- 
  na.replace(MTX2_data$with, replace = FALSE)

MTX2_data <- 
  MTX2_data[!MTX2_data$with, -15]

# Replace NAs in the MTX colony size by 0
MTX2_data$area <- 
  na.replace(MTX2_data$area, 0)

# Histrogram of the distribution of MTX colony area
ggplot(data = MTX2_data)+
  geom_histogram(mapping = aes(x = area),
                 binwidth = 20)+
  theme_minimal()

### Export clean MTX2 data
write.csv(x = MTX2_data, 
          file = '~/ancSH3_paper/SupplementaryMaterial/SupplementaryData1/free_SH3_RD/MTX2_data_clean.csv', 
          quote = TRUE, 
          fileEncoding = 'UTF-8')


#############################
## MTX data transformation ##
#############################
library(viridis)

MTX2.data <- 
  read.csv(file = './MTX2_data_clean.csv', 
           fileEncoding = 'UTF-8', )[,-1]

# Columns removal and transformation
MTX2.data$X <- NULL
MTX2.data$X.x <- NULL
MTX2.data$X.y <- NULL
MTX2.data$plate <- as.factor(MTX2.data$plate)

# Adjust area = 0 to area = 1 for logarithm transformation
MTX2.data %<>% mutate(adjust = area + 1)

# Transform colony adjusted area in log2 scale
MTX2.data$log2.area <- log2(MTX2.data$adjust)

# Attribute [estradiol]nM to plates
MTX2.data$estradiol <- 
  factor(MTX2.data$plate, 
         levels = 1:16, 
         labels = c(0,0,10,10,20,20,30,30,40,40,60,60,80,80,100,100))

# Distribution of log2(colony area) per plate

ggplot(data = MTX2.data) +
  geom_density(mapping = aes(x = area, group = plate, color = estradiol))+
  theme_minimal()+
  theme(legend.position = 'none')+
  geom_vline(xintercept = 300, color = 'orangered', linewidth = 1)+
  #xlim(0, 14)+
  theme_bw()+
 # xlab(expression(paste(log[2], '(colony area)')))+
  ylab('Density')+
  scale_color_viridis(option = 'G', discrete = T)+
  theme(legend.position = 'bottom')+
  guides(color = guide_legend(nrow = 2, 
                              title = expression(paste('[Estradiol] ', mu, 'M    ', sep = ''))))

# Remove the empty position
MTX2.data <-  subset(MTX2.data, 
                     MTX2.data$log2.area >= 3)

# Save the data frame object
saveRDS(MTX2.data, file = './MTX2_trans.rds')

###############################
## Normalization : PCA score ##
###############################
library(ggpubr)

# Important to compare the plates with each other
MTX2.list <- readRDS('./MTX2_trans.rds')

  
#remove positions that grew at 0uM estradiol
position_sup <- 
  MTX2.list[( MTX2.list$area > 100 & MTX2.list$plate %in% c(1,2) & MTX2.list$baits != 'border'), c('row', 'column')]       

MTX2.list <- 
  MTX2.list[!( MTX2.list$area > 100 & MTX2.list$plate %in% c(1,2) &MTX2.list$baits != 'border'),]          

position_sup <- 
  paste(position_sup$row, position_sup$column, sep  = '.')

MTX2.list <- 
  MTX2.list[!paste(MTX2.list$row, MTX2.list$column, sep = '.') %in% position_sup, ]


# Calculation of min/max for each plate
  MTX2.list %<>% 
    group_by(plate) %>% 
    mutate(max = max(log2.area, na.rm = TRUE))%>%
    ungroup()
  
  MTX2.list %<>% 
    group_by(plate) %>% 
    mutate(min = min(log2.area, na.rm = TRUE))%>%
    ungroup() 

  #Withdrawal of the border
  MTX2.list %<>% filter(preys != 'border')  
  
# Calculation of standardized data using the min/max calculated (PCA score)
 MTX2.list %<>% 
  mutate(norm = ((log2.area - min)/(max-min)))


# Verification of the correlation between technical replicates
# technical replicate plate combination : 1&5, 2&6, 3&7, 4&8
 dfrep1 = MTX2.list %>% filter(plate %in% c(1,3,5,7,9,11,13,15))
 dfrep2 = MTX2.list %>% filter(plate %in% c(2,4,6,8,10,12,14,16))
 
 dfrep1 %<>% mutate(baitXprey_1 = interaction(baits, preys,tag)) %>% select(baitXprey_1, norm, log2.area, estradiol)
 
 dfrep2 %<>% mutate(baitXprey_2 = interaction(baits, preys, tag)) %>% select(baitXprey_2, norm, log2.area, estradiol)
 
 crep <-  merge(dfrep1,
                dfrep2,
                by.x=c("baitXprey_1", 'estradiol'),
                by.y=c("baitXprey_2", 'estradiol'))
  
sf5a <-   
 ggplot(data = crep, aes(x = norm.x, y = norm.y)) +
   facet_wrap(~estradiol, nrow = 2)+
   geom_point(aes(x = norm.x, y = norm.y), alpha = 0.2)+
   stat_cor(method = 'spearman', cor.coef.name = c('r'), 
            label.sep = '\n',  label.x.npc = 'left', hjust = 0, label.y = 0.87)+
   xlab('technical replicate 1')+
   ylab('technical replicate 2')+
   scale_x_continuous(breaks  = c(0 , 1), limits = c(0, 1))+
   scale_y_continuous(breaks  = c(0, 1), limits = c(0, 1))+
   theme_bw()+
   theme(
     legend.text = element_text(size = 14),
     legend.title = element_text(size = 16),
     axis.title = element_text(size = 14),
     axis.text = element_text(size =12),
     axis.text.x = element_text(hjust = 0.7),
     strip.text = element_text(size = 16), 
     panel.grid.major = element_blank(), panel.grid.minor = element_blank()
   )

saveRDS(sf5a, file = '~/ancSH3_paper/SupplementaryMaterial/FigurePanels/SuppFig5A.rds')
 
# Remove plates 10 and 14, with problem with estradiol
 MTX2.list <-   
   MTX2.list[!(MTX2.list$plate %in% c(10, 14)), ] 

# Export normalized data
saveRDS(MTX2.list, file = './MTX2_norm.rds')   

###########################
## PPI score computation ##
###########################

MTX2.list <- readRDS(file = './MTX2_norm.rds')
MTX2.list.rep <- vector(mode = 'list', length = 1)

# Compute the median of biological replicates (unique prey-bait combination)  
MTX2.list.rep <-  
  MTX2.list%>%
  group_by(baits, preys, tag, estradiol) %>%
  dplyr::summarise(n(), medsize = median(adjust ,na.rm = TRUE ), 
            medrep = median(norm, na.rm = TRUE ))

# Transform columns
MTX2.list.rep%<>% mutate(strain= str_c(baits, preys, tag, estradiol, sep = '.'))
MTX2.list.rep %<>% mutate(log2medsize = log2(medsize))

# Create object with PCA and PPI scores

MTX2.list.rep <-   
  merge(MTX2.list,
        MTX2.list.rep[, c('baits', 'preys', 'tag', 'estradiol','strain', 'medsize','log2medsize','medrep','n()')], 
        by = c('baits', 'preys','tag', 'estradiol'))


# Treshold the data based on [estradiol] 100nM data, 
# Remove all position that did not grow at 100nM

x <- c(390) # colony area treshold 

MTX100 <- subset(MTX2.list.rep,
                 subset = estradiol == 100)


v <- vector(mode = 'character', length = 0)

for(j in unique(MTX100$strain)){
  test <-
    unique(subset(MTX100,
                  subset = strain == j, 
                  select = c(1:4,18,21,22)))
  if(test$medrep < log2(x)){
    v <- c(v, j)
  }
}



v <-
  unique(gsub(v, pattern = '.100', replacement = '', fixed = T))
v <-
  paste0(rep(v, each = 8),'.' ,rep(c(0,10,20,30,40,60,80,100), length = 792))
MTX2.list.rep <-  
  MTX2.list.rep[MTX2.list.rep$strain %in% v , ]

#  Select interactions with more than 1 replicate
MTX2.list.rep <- 
  subset(MTX2.list.rep, 
         subset = 'n()' >= 2)

# Export the data (used for Supplementary Material)
saveRDS(MTX2.list.rep , file = './MTX2data_free_SH3.rds')

